# Generated by Django 5.1 on 2025-01-06 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movies",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 6, 17, 30, 46, 696073, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
