# Generated by Django 5.1 on 2025-01-06 17:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movies_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
